### PR TITLE
Changed copyright year

### PR DESCRIPTION
**Pull request by SACViper**
Changed all files copyright year

### CODE REVIEW

**Comment by emmett1** [comment]
Why not '2019 - 2020' ?

**Comment by SACViper** [comment]
Actually it should be from when you started the project till now,e.g 2010 - 2020 all the work you have done on website is the property of Venom Linux, 

> New versions or editions of works should contain the publication date of the new version or edition. For constantly evolving websites and blogs that contain works published over several years, the notice may include a range of years (e.g., 2009–2019), starting from the date of the oldest published elements and ending with the date of the newest published elements.
[https://www.copyrightlaws.com/copyright-symbol-notice-year/](url)

**Comment by emmett1** [comment]
The project is started around 2016, but the website just started last year (2019).

**Comment by SACViper** [comment]
ok then then we can put it 2019 - 2020 i can go ahead make changes

**Comment by emmett1** [comment]
Ok

**Pull request merged**
